# Generated by Django 4.1.6 on 2023-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_cartitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
